### PR TITLE
Redesign webpage

### PR DESCRIPTION
**Pull request by disnet**
Use a basic bootstrap template so we have nice nav bar across all the pages. Drop asciidoc in favor of just markdown for the docs

### CODE REVIEW

**Comment by disnet** [comment]
The status check has a link to a deploy preview if you want to see what this looks like before we merge.

**Review by gabejohnson — CHANGES_REQUESTED** [review]
Very nice! Can you add Octocat to the GitHub link?

**Comment by disnet** [comment]
Octocat added!

**Review by gabejohnson — APPROVED** [review]

**Review by gabejohnson — CHANGES_REQUESTED** [review]
Section headers are being hidden behind the top navbar https://deploy-preview-1--sweetjs.netlify.com/doc/reference#helpers. Note that "Helpers" is hidden.

**Comment by disnet** [comment]
No real need to keep the navbar fixed so I'll just leave it at the top. Also took the opportunity to add anchor links next to all the headings.

**Comment by disnet** [comment]
I also just published a separate helpers package so I'm now referring to `@sweet-js/helpers` instead of `sweet.js/helpers`.

**Review by gabejohnson — APPROVED** [review]

**Pull request merged**
